### ISSUE TITLE
unique name

### ISSUE THREAD

**Issue by stickylab** [danqzq/unity-leaderboard-creator#1]
how to check if there is already name 

![image](https://github.com/danqzq/unity-leaderboard-creator/assets/87752832/85faf7f0-3461-43a9-a338-653fcdb35ec0)

**Comment by danqzq** [comment]
The UploadNewEntry function has an errorCallback overload which will return an error upon submitting an entry with an existing name, and if Unique Usernames is enabled on the leaderboard.

https://github.com/danqzq/unity-leaderboard-creator#uploading-and-modifying-leaderboard-entries
