### ISSUE TITLE
Im having this problem

### ISSUE THREAD

**Issue by SaraCastro132** [danqzq/unity-leaderboard-creator#2]
[LeaderboardCreator] Service Unavailable: <!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>
UnityEngine.Debug:LogError (object)
Dan.Main.LeaderboardCreator:LogError (string) (at Assets/LeaderboardCreator/Scripts/Main/LeaderboardCreator.cs:314)
Dan.Main.LeaderboardCreatorBehaviour:HandleError (UnityEngine.Networking.UnityWebRequest) (at Assets/LeaderboardCreator/Scripts/Main/LeaderboardCreatorBehaviour.cs:176)
Dan.Main.LeaderboardCreatorBehaviour/<>c__DisplayClass9_0:<SendGetRequest>b__0 (bool) (at Assets/LeaderboardCreator/Scripts/Main/LeaderboardCreatorBehaviour.cs:123)
Dan.Main.LeaderboardCreatorBehaviour/<HandleRequest>d__12:MoveNext () (at Assets/LeaderboardCreator/Scripts/Main/LeaderboardCreatorBehaviour.cs:155)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

**Comment by danqzq** [comment]
The servers sometimes crash due to mass use, but I am working on eliminating this issue. Sorry for the inconveniences.
