### ISSUE TITLE
issue when upload an entry 

### ISSUE THREAD

**Issue by JaredL3vi** [danqzq/unity-leaderboard-creator#4]
when I upload an entry with the name 0 then I upload a new entry with the name 1 regardless of its points or extra value it over rights entry 0.

this is my upload code

Leaderboards.TutorialLeaderboard.UploadNewEntry(_world, _score, _username);

yes, I know that the extra and username strings are in the wrong spots that is my intention. I want to have one score for each world.

In rereading the documentation I believe it is because of the unique identifier. This leader board will not allow the player to edit a score someone else uploaded. How ever I think you should be able to set no unique identifier in the my leader board tab. That way anyone can upload a new score to overwrite the old score with the same name.

**Comment by danqzq** [comment]
I believe the documentation has the answer to your concern:

https://github.com/danqzq/unity-leaderboard-creator#my-leaderboard-entry-keeps-getting-overridden--i-can-only-upload-one-entry-why-is-that

**Comment by JaredL3vi** [comment]
well the thing is that, I was hoping to lock it to one high score per level. with this work around you can upload as many scores for the same level as you want because you cant edit the one that is already on the board.

is there a way to either delete entry by index or set every user to have the same identifier. I think I could achieve what I'm looking for with either ability.
