### ISSUE TITLE
Teams Leaderboard

### ISSUE THREAD

**Issue by omariosman** [danqzq/unity-leaderboard-creator#5]
@danqzq 
Can I use this leaderboard to make a **Teams Leaderboard** not individual leaderboard where every team has an entry in the leaderboard?

For example. if I have player 1 and player 2 both belongs to the same team called **Team1**
Then both of the players can should be able to update the score of then entry of Team1?

From my understanding to the docs that this is not applicable because the design of this leaderboard allows only each user to update his own entry by a unique identifier

**Comment by danqzq** [comment]
Hey, unfortunately this tool was not built for what you are asking for. However, you are not the first one with this inquiry, and some users have tackled this issue. One approach you could take is by letting the master client/host to upload a single entry for the whole team's score, and appending the other players' names in the "Extra" field of the entry.
